### ISSUE TITLE
Question about Adafruit GFX Dependency

### ISSUE THREAD

**Issue by KonstantinSchubert** [martinberlin/CalEPD#3]
Hi Martin,

I want use the library to write an existing byte array of pixel data to the 7.5inch 480 * 800 display from Waveshare on the ESP32.
(I am creating the byte array server-side and then downloading it on the ESP32.)

Since I already have the pre-rendered pixels, do I still need the Adafruit GFX dependency? Or can I use CalEPD without it?

**Comment by martinberlin** [comment]
Actually if you pre build the internal buffer outside and manage to load it somehow and send it per SPI you should not need Adafruit GFX. 
It won't bother to leave it there, just try to accomplish sending the received buffer per SPI first, and see if that works as you expect. But of course if you need more memory, you can just reduce or eliminate the _buffer that in that display takes 800*480/8 good 48 Kb of RAM. But keep in mind that if you need to draw something on the top, or an user interface/message, etc, then you need to have GFX. So IMHO I would leave it there since with an ESP32 you have enough memory for many other things still and in the worst case you can use a model with PSRAM.

Keep me updated on how that goes

**Comment by KonstantinSchubert** [comment]
Hi, 
I removed the adafruit gfx dependency and the drawing-related functions in the epd.h subclasses and it all compiles well. 
Unfortunately I don't have success with drawing yet "Busy Timeout", but I think that's unrelated.

**Comment by KonstantinSchubert** [comment]
You are right though that leaving in the adafruit gfx doesn't really hurt. I think my desire to remove is is more for aesthetic reasons: Following the SRP principle, the esp.h class should not handle IO *and* render.

**Comment by KonstantinSchubert** [comment]
Thank you for your helpful answer!

**Comment by martinberlin** [comment]
Good luck, keep me aware if you can make it!
I'm not really a C++ ultra conservative performance seeker. I follow my own OOP principles that may not follow any other principles. 
But I'm willing to see what others do with my ideas. So please make it open source so we can learn from what you do also.
Make sure to send the full buffer and the right SPI command for this display to refresh.
